create table if not exists public.agents (
  id bigint generated by default as identity primary key,
  code text not null unique,
  full_name text not null,
  phone text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  device_id text not null unique,
  label text not null,
  agent_id bigint references public.agents(id) on delete set null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  device_id text not null references public.devices(device_id) on delete restrict,
  agent_id bigint not null references public.agents(id) on delete restrict,
  service_type text not null,
  route text not null,
  amount integer not null,
  payment_mode text not null default 'cash',
  passenger_name text,
  passenger_phone text,
  package_details text,
  receiver_name text,
  receiver_phone text,
  ticket_text text,
  created_at timestamptz not null default now()
);

create index if not exists idx_devices_agent_id on public.devices(agent_id);
create index if not exists idx_tickets_agent_id on public.tickets(agent_id);
create index if not exists idx_tickets_device_id on public.tickets(device_id);
